language: python
python:
    - "2.7"
install:
    - pip install -q -e . --use-mirrors
    - pip install -q Django==1.6.11 --use-mirrors
    - pip install pep8 --use-mirrors
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 src"
script:
    - python setup.py test

